config/routes.rb
Rails.application.routes.draw do

  get 'productos/index'
  get 'productos/show'
  devise_for :users
  root to: "home#dasboard"

  resources :productos
  # devise_scope :user do
  #   get '/logout',  :to => 'sessions#destroy'
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compra.rb
class Compra < ApplicationRecord
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/organizacion.rb
class Organizacion < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :tipo
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
end

app/models/reclamo.rb
class Reclamo < ApplicationRecord
end

app/models/registro.rb
class Registro < ApplicationRecord
  belongs_to :rol
  has_many :usuarios
end

app/models/registrotrabajadore.rb
class Registrotrabajadore < ApplicationRecord
end

app/models/stoockdeproducto.rb
class Stoockdeproducto < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
  has_many :productos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!

  def dasboard

    
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController

  before_action :authenticate_user!

  # before_action :authenticate_user!, only: [:index]

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/home/dasboard.html.erb
<h1>Home#dasboard</h1>
<p>Find me in app/views/home/dasboard.html.erb</p>



<%= link_to "Ver todos los productos", productos_index_path %>

<%= form_for(current_user,
    url: destroy_user_session_path, html: { method: :delete }) do |f| %>
    <%= f.submit "Log out" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyectoprueba</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <!-- Include all compiled plugins (below), or include individual files as needed -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/productos/index.html.erb
<h1>Productos#index</h1>
<p>Find me in app/views/productos/index.html.erb</p>


<%= link_to "dasboard", root_path %>

app/views/productos/show.html.erb
<h1>Productos#show</h1>
<p>Find me in app/views/productos/show.html.erb</p>